# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

MAX = 4000000
terms = [1, 2]
sum = 0

while terms.last <= MAX
  sum += terms.last if terms.last.even?

  next_term = terms.sum

  terms.shift
  terms << next_term
end

puts sum

# Time: 0m1.331s